### ISSUE TITLE
Copies improvement - Voter perspective

### ISSUE THREAD

**Issue by ferranrego** [decidim-vocdoni/decidim-module-vocdoni#32]
**In the _Authenticate_ page, where the user verifies the vote:**
Replace:
> Check status
<img width="371" alt="image" src="https://user-images.githubusercontent.com/3515290/219735004-ca42c44a-bde6-4c47-9723-42f2a70f4ebd.png">

With: 
> Access

**In the _Vote Submission_ page:**
Replace:
> Your ballot is being submitted to the Vocdoni API.

With:
> Your vote is being processed using Vocdoni Protocol, a secure digital voting technology.
> Be patient, this process can take some time

**In the _Vote receipt_ page:**
Replace:
> Your vote has been sent

With:
> Your vote has been cast

Replace:
> You can check your vote using the Vocdoni Explorer portal.

With:
> Your vote has been cast successfully! You can store the following receipt as proof of your vote's inclusion at any time and check it using the Vocdoni Explorer.
Your vote receipt is: de8f9a3af354176e7bc93bb0992282c72253c701f29878931115c2ebe02aff01

Nice to have: 
I would add a copy action icon at the left of the identifier, to make it easier to copy.
![image](https://user-images.githubusercontent.com/3515290/219741255-23184d01-45e0-4f52-8167-586bac431652.png)
I would replace the "Check my vote" with a  "Verify your vote" but as a button on the left side of "Exit the voting booth"

**Comment by andreslucena** [comment]
> **In the _Authenticate_ page, where the user verifies the vote:**
> Replace:
> > Check status
> 
> With: 
> > Access

Done: 

![image](https://user-images.githubusercontent.com/717367/220097850-3482d062-8cac-4d09-85b2-33b1e8a2c236.png)

> **In the _Vote Submission_ page:**
> Replace:
> > Your ballot is being submitted to the Vocdoni API.
> 
> With:
> > Your vote is being processed using Vocdoni Protocol, a secure digital voting technology.
> > Be patient, this process can take some time

Done: 

![image](https://user-images.githubusercontent.com/717367/220098118-e2a058c5-bd68-45dc-a062-7aded7342e02.png)


**In the _Vote receipt_ page:**
Replace:
> Your vote has been sent

> With:
> > Your vote has been cast
> 
> Replace:
> > You can check your vote using the Vocdoni Explorer portal.
> 
> With:
> > Your vote has been cast successfully! You can store the following receipt as proof of your vote's inclusion at any time and check it using the Vocdoni Explorer.
> Your vote receipt is: de8f9a3af354176e7bc93bb0992282c72253c701f29878931115c2ebe02aff01
> 
> Nice to have: 
> I would add a copy action icon at the left of the identifier, to make it easier to copy.

Done:

![image](https://user-images.githubusercontent.com/717367/220098756-8774ce7a-6f6a-4ad7-a34f-8dd43e503d09.png)

> I would replace the "Check my vote" with a  "Verify your vote" but as a button on the left side of "Exit the voting booth"

Just talked with @carolromero about this one: we're against adding two call to actions, as that's an usability problem and pollutes the interface. As an alternative, we could change the "Exit the voting booth" to "Verify my vote" and viceversa, so the main CTA is to verify the vote and the link is to "exit the voting booth" or something like that.
