### ISSUE TITLE
Copies - Admin manager

### ISSUE THREAD

**Issue by ferranrego** [decidim-vocdoni/decidim-module-vocdoni#33]
**In the _Components_ -> _Elections (Vocdoni)_ page:**

Replace:
> This component allows you to create and manage elections using the Vocdoni platform. Vocdoni is a secure digital voting solution using decentralized technologies. The voting protocol which powers the platform is designed to be universally verifiable, secure, and resistant to attack and censorship through the use of blockchain technology, together with decentralized technologies and cryptographic mechanisms, such as zero-knowledge proofs.

For:
> With this voting module, you can easily organize a wide range of voting processes with high guarantees. The module utilizes the Vocdoni Protocol, an open-source voting technology to organize elections with the highest standards of security, universal verifiability, censorship-resistance, and anonymity. To learn more about Vocdoni, visit their website [here](https://vocdoni.io/).

**In the  _Components_ -> _Elections (Vocdoni)_ -> Edit:**
- Add (optional) on
- Keep (optional) on the  "Image" field (as it will be optional

**In the _Components_ -> _Elections (Vocdoni)_ -> _Census_ page:**
> To prepare the census for your election, you must create a file in CSV format. Each column in the file should correspond to an attribute that the voter will need to provide for authentication. For example, the first column could be the email address, and the second column could be the date of birth in the format YYYY-MM-DD.
>To create the CSV file, you can use any spreadsheet software, such as LibreOffice Calc, Microsoft Excel, or Google Sheets. After creating the file, be sure to save it in CSV format.

**In the _Steps Dashboard_
- Add this text over "Setup vote": Your voting process is secured using the advanced digital voting technology of the Vocdoni Protocol. Please be patient, as the set-up process may take some time.
- When the process is created succesfully -> Instead of sending the user to the Vocdoni Explorer, send it to the landing of that voting process on Decidim.

Add the following text and the Vocdoni logo at the bottom of all pages of this module:
- This module makes use of Vocdoni Protocol, an open-source voting technology to organize elections with the highest standards of security, universal verifiability, censorship-resistance, and anonymity.

**Comment by andreslucena** [comment]
> **In the _Components_ -> _Elections (Vocdoni)_ page:**
> 
> Replace:
> > This component allows you to create and manage elections using the Vocdoni platform. Vocdoni is a secure digital voting solution using decentralized technologies. The voting protocol which powers the platform is designed to be universally verifiable, secure, and resistant to attack and censorship through the use of blockchain technology, together with decentralized technologies and cryptographic mechanisms, such as zero-knowledge proofs.
> 
> For:
> > With this voting module, you can easily organize a wide range of voting processes with high guarantees. The module utilizes the Vocdoni Protocol, an open-source voting technology to organize elections with the highest standards of security, universal verifiability, censorship-resistance, and anonymity. To learn more about Vocdoni, visit their website [here](https://vocdoni.io/).

Done: 

![Selection_533](https://user-images.githubusercontent.com/717367/220100096-3ea11243-9af4-427a-b414-6a113c507144.png)

Note that I've changed the last phrase as links with the "here" word are not accessible. 

> **In the  _Components_ -> _Elections (Vocdoni)_ -> Edit:**
> - Add (optional) on
> - Keep (optional) on the  "Image" field (as it will be optional

I think I don't fully understand this one; if you're referring to the " The election has at least one photo." and the image gallery (optional) in the Edit form, I prefer to leave it as is and change it once the API doesn't make the image mandatory. 


> **In the _Components_ -> _Elections (Vocdoni)_ -> _Census_ page:**
> > To prepare the census for your election, you must create a file in CSV format. Each column in the file should correspond to an attribute that the voter will need to provide for authentication. For example, the first column could be the email address, and the second column could be the date of birth in the format YYYY-MM-DD.
> >To create the CSV file, you can use any spreadsheet software, such as LibreOffice Calc, Microsoft Excel, or Google Sheets. After creating the file, be sure to save it in CSV format.

This isn't how it actually works, in the Decidim side is hardcoded, meaning that it will always need to be an email and date of birth fields. This is the same on other Decidim CSV importers. I think it'd be a great feature to have, but it can be difficult to implement on the current grant, as there are multiple implementation details to take into account. For instance:

1.  the type of field, now for the "date of birth" we're using three different fields for day/month/year and we'd need to configure this on the admin.  
2. the translations, as we'd need to make the admin aware of these fields and to make them translatables

> **In the _Steps Dashboard_
> - Add this text over "Setup vote": Your voting process is secured using the advanced digital voting technology of the Vocdoni Protocol. Please be patient, as the set-up process may take some time.
> - When the process is created succesfully -> Instead of sending the user to the Vocdoni Explorer, send it to the landing of that voting process on Decidim.

Added in "Setup election" as there isn't any "Setup vote" in Steps dashboard. (Please, correct me if I'm wrong)

![image](https://user-images.githubusercontent.com/717367/220103463-00034d06-2830-4e36-9cec-4eb2003bfda3.png)

> - When the process is created succesfully -> Instead of sending the user to the Vocdoni Explorer, send it to the landing of that voting process on Decidim.

I think it's necessary to have both links, with the primary button being the "Preview landing page". This is my proposal: 

![image](https://user-images.githubusercontent.com/717367/220109375-3b070770-0c12-4d1a-8c72-ddc2ceb833d4.png)



> Add the following text and the Vocdoni logo at the bottom of all pages of this module:
> - This module makes use of Vocdoni Protocol, an open-source voting technology to organize elections with the highest standards of security, universal verifiability, censorship-resistance, and anonymity.

At the moment is only in the steps page: 

![image](https://user-images.githubusercontent.com/717367/220104183-cf46838a-00ba-4d00-8cc9-f6bfd2bcd5bc.png)

Let me know if you're ok with the current UI and we can implement it on the other pages afterwards.

**Comment by ferranrego** [comment]
Regarding the bottom message on each page it’s good! We should replace the current logo used by this one (new branding)
https://aragonorg.notion.site/Identificadores-38c6721722854acdbbfb59209aa305a0

the rest looks fine! 😄

**Comment by andreslucena** [comment]
> Regarding the bottom message on each page it’s good! We should replace the current logo used by this one (new branding) [aragonorg.notion.site/Identificadores-38c6721722854acdbbfb59209aa305a0](https://aragonorg.notion.site/Identificadores-38c6721722854acdbbfb59209aa305a0

Done:

![image](https://user-images.githubusercontent.com/717367/220326602-88139eac-ca2d-4c8b-ad57-6b21ad295b2a.png)
