### ISSUE TITLE
Server error when running an election with setting "secret until the end" enabled

### ISSUE THREAD

**Issue by carolromero** [decidim-vocdoni/decidim-module-vocdoni#39]
When running an election with the "Secret until the end" setting enabled, after the voting period is over, it returns a 500 error when publishing the results.

1. Create a new election with the option "Secret until the end" activated
2. Create one question and at least two answers
3. Upload de census
4. Setup de election
5. Once the voting period has started, submit a few votes
6. When the voting period has ended, click on "Publish results"
7. See error

**Comment by andreslucena** [comment]
This should be fixed with the last deployed version, can you check it out 🙏🏽 ?

**Comment by carolromero** [comment]
Checked and fixed now :clap: :clap:
