### ISSUE TITLE
Ending an election doesn't work 

### ISSUE THREAD

**Issue by carolromero** [decidim-vocdoni/decidim-module-vocdoni#46]
As an admin, when I try to end an election prematurely, I get a success message (*), but in the frontend it still shows as active. The voting booth remains open, but it returns the following message once the credentials are entered:
"Currently the election is not open for voting. Try again later."

(*) The success message says it's been _paused_ and it should say _ended_.

 ![](https://i.imgur.com/qK7zvWG.png)
 

1. Create and setup an interruptible election
2. Submit a couple of votes
3. End the election manually
4. Go to the public view
5. See that the election is displayed as active and the voting booth open
6. Enter some valid credentials and see the message: "Currently the election is not open for voting. Try again later."

![](https://i.imgur.com/v26YGXz.png)

**Additional context**
Vocdoni SDK version: v0.0.4-alpha

**Comment by andreslucena** [comment]
This should be fixed with the last deployed version, can you check it out 🙏🏽 ?
