### ISSUE TITLE
Update @vocdoni/sdk to v0.0.12

### ISSUE THREAD

**Issue by paarals** [decidim-vocdoni/decidim-module-vocdoni#51]
- [x] Update `package.json` with the latest version of the vocdoni sdk (check https://github.com/vocdoni/vocdoni-sdk/tags).
- [x] Specs passing

**Comment by paarals** [comment]
i'm reopening the issue due the new version of sdk. @antopalidi will work on that again. 
thanks!

**Comment by andreslucena** [comment]
I'm closing this one and changing the title so it's easier to keep track of. I've created a new one at #66
