### ISSUE TITLE
Manually start an election

### ISSUE THREAD

**Issue by andreslucena** [decidim-vocdoni/decidim-module-vocdoni#58]
Ref: VOC-SEC-05

As an administrator, there are elections that don't have a defined start date time, but that start on an administrator action (for instance, when a face to face meeting starts). For these cases, I need to be able to manually start an election.

This means that we need to change the current form, so the start date configuration will have a checkbox, with three options:

1. Start on a specific date
2. Start manually

Each of these actions will work as this:

|Option|Description|
|---|---|
|1. Start on a specific date |Current behavior. When selected, a date time selector will appear that allows the admin to configure the `start_time` for the election. Regarding the `electionType` field, it'll set it up with an autoStart value of "true".|
|2. Start manually  |It will not start the election automatically. When selected, the date time selector will disappear. It will set up the election without any `start_time`. It'll set up the election with state "Paused" and it'll allow the administrator to "Start" the election with a button (similarly to the controls that we offer when the election is Interruptible, see #47). Regarding the `electionType` field, it'll set it up with an `autoStart` value of "false".

### Mockups

![](https://i.imgur.com/GwVYWYb.png)

### Acceptance criteria

- [x] Given that I'm an administrator,
      When I create a new Election,
      Then I can create it with the "Start on a specific date" option,
      And I see the `start_time` date time picker when editing or creating the Election
      And when I set up the Election, this election starts at the configured date and time,
      And the start date is showed publicly.
- [x] Given that I'm an administrator,
      When I create a new Election,
      Then I can create it with the "Start manually" option,
      And I don't see the `start_time` date time picker when editing or creating the Election
      And when I set up the Election, this election doesn't start,
      And I have a button to "Start election",
      And the start date is showed publicly.
- [x] Given that I'm a visitor and there's an Election created with the "Start manually" option
      When I go to see a published election metadata (i.e. cards/lists and single election page)
      Then I see that this election doesn't have a start date
- [x] Given that I'm a developer,
      When I consume the GraphQL API,
      Then it works with each of these options
- [x] Given that I'm a developer,
      When I run the seeds,
      Then there are some elections with each of these options

**Comment by microstudi** [comment]
I'm leaving here some mockups on this one. Also I think we should add some more explanations in the setup step, we could use this one to add them:

1. Setup election added explanations:
![Screenshot from 2023-06-21 12-28-33](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/1401520/b19b5548-306a-41fe-8ac9-4913c858e55b)

2. Configure the start date:
![Screenshot from 2023-06-21 12-09-48](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/1401520/e37096fc-1759-4ee7-884d-5953b6cf130e)

3. Start the election:
![Screenshot from 2023-06-21 12-17-51](https://github.com/decidim-vocdoni/decidim-module-vocdoni/assets/1401520/a61df461-9ef9-4061-9b1f-281f7ca66892)

What do you think @carolromero @andreslucena ?

**Comment by andreslucena** [comment]
For me it looks 👌🏽 


> Configure the start date:

There's a bug here, as in the disabled input datetime it's showing the full date with the timezone (+0200), but I guess it's just a quick mockup 😄

**Comment by microstudi** [comment]
Now that you say it, you're right. Strange...

**Comment by carolromero** [comment]
it looks awesome @microstudi :heart_eyes:.
I see we have changed a bit the transition from the last screen of creating an election to the dashboard, but this way it works fine too!
