### ISSUE TITLE
Credit renewal flow

### ISSUE THREAD

**Issue by andreslucena** [decidim-vocdoni/decidim-module-vocdoni#73]
Ref: VOC-SEC-06

When the vocdoni environment is set up to production, there are costs for using the Vocdoni platform.

```markdown=
## Pricing

The usage of the Vocdoni platform has some economic costs, as its using a Blockchain.

For using it in a production environment with guaranties, you need to contact the Decidim Association to vocdoni [at] decidim.org asking for a pricing. It depends in your usage (mostly in your census size).
```

As there could be other resellers and not only the Decidim Association, this needs to be configured through the ENV variables:

1. VOCDONI_RESELLER_NAME
- Description: The name of the Vocdoni reseller, the organization that manages the tokens to work with the Vocdoni platform
- Default value: `Decidim Association`

2. VOCDONI_RESELLER_EMAIL
- Description: The email of the Vocdoni reseller
- Default value: `vocdoni@decidim.org`

These configurations need to be in the README. 

When the administrator goes to the Vocdoni component page and there isn't any token, they'll see the announcement:

> The usage of the Vocdoni platform has costs. Please get in touch with <a href="mailto:<VOCDONI_RESELLER_EMAIL>">VOCDONI_RESELLER_NAME</a> to ask for a quote. You need to also tell them your organization address: <CURRENT_ORGANIZATION_VOCDONI_ADDRESS>

### Acceptance criteria

- [ ] As an implementer, I have some instructions in the README file with the Pricing sections
- [ ] As an implementer, I have the ENV variables in the README
- [ ] As an implementer, I can configure these ENV variables
- [ ] As an administrator, when running in production environment, if there isn't any token then I see the announcement

**Comment by microstudi** [comment]
@andreslucena @carolromero shoudn't this story include a form to set your ethereum organization address?

**Comment by andreslucena** [comment]
> @andreslucena @carolromero shoudn't this story include a form to set your ethereum organization address?

As we've talked offline: we believe that specially at the beginning 90% of the administrators would not know whats a wallet, and if we could get away with a random wallet would be great, to not add an overhead on the configuration. Your proposal can be done after this first implementation.
