### ISSUE TITLE
Redesign update

### ISSUE THREAD

**Issue by andreslucena** [decidim-vocdoni/decidim-module-vocdoni#74]
Ref: VOC-SEC-08

During 2022 and 2023, Decidim has been working in a full redesign of the UI, both in the admin panel and in the participant facing UI. 

On December 2023, v0.28.0 was released with the new design. We need to update the HTML/CSS/JS to the new UI. As most of the asssets were extracted and adapted from `decidim-elections`, that's a good starting point for the adaptation.

https://github.com/decidim/decidim/tree/develop/decidim-elections
 
### Acceptance criteria

- [ ] As an implementer, I can use the module with decidim v0.27 
- [ ] As an implementer, I can use the module with decidim v0.28
- [ ] As an implementer, I have instructions for the installation in both of these versions

**Comment by microstudi** [comment]
This should be completed by #78
